
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-20T18:28:02-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7b724f8d68cb8d1d655308c793550311231545dc",
 "version": "4.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
